### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by mhrechkin** [nickolay-grechkin/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by KennyLVM** [comment]
2020-present Geralt performs small freelance orders.
2019 Geralt is invited to star in a series that tells about his great exploits. He agrees and perfectly fulfills the role of himself. 
2017 The next step in the Witcher's career ordering a Devil by the Well. For this order, the Witcher has to brew a potion against ghosts. The battle turned out to be protracted and tiring, but Geralt defeats the monster.
2016 Geralt receives an order for a griffin that attacks the inhabitants of Velen. Going to the place where the beast was last seen - in the vicinity of the village of Vereskovka, the witcher finds the nest and kill the creature.
2015 Gwynbleidd faces evil gargoyles. The Witcher learned that gargoyles are magical creatures that guard the city. They attacked everyone who entered the territory. He rubbed off the soles of his boots and dulled the blade, but got rid of the gargoyles.
2013 Destroys naker's nest with bombs.
2012 The Witcher fights Azar Javid, the leader of the bandits who attacked the fortress of Kaer Morhen. Heralt defeats him.
2010 White Wolf  defeats the monster in the sewers - the cockatrix. 
2009 Deal with the mysterious Beast, which terrorizes the inhabitants of the suburb of Vizima, summoning ghostly dogs - barghests at night.
2007 Geralt's story begins this year, since he does not remember his story before this year due to amnesia. 
The fortress Kaer Morhen in which Geralt is undergoing rehabilitation is attacked by a squad of bandits who want to steal the secret mutagens of the witchers. He decides to stop them.
